# Generated by Django 5.0 on 2024-01-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontonkuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Userid',
            field=models.CharField(max_length=30),
        ),
    ]
